Repository offensive-vk/AwesomeTesting, pull requests merged in 2024-08, with the labels that each got.

#37 Add Mirror Rule - Gitlab
  .github/workflows/mirror.yml
Labels: enhancement, sync-success

#36 Updated CI Workflows.
  .github/workflows/docker-image.yml
  .github/workflows/docker-publish.yml
  .github/workflows/linux.yml
  .github/workflows/macos.yml
  .github/workflows/windows.yml
Labels: enhancement, help wanted

#44 Update All Actions - Final Time.
  .github/workflows/docker-image.yml
  .github/workflows/docker-publish.yml
  .github/workflows/linux.yml
  .github/workflows/macos.yml
  .github/workflows/mirror.yml
  .github/workflows/windows.yml
Labels: enhancement
